### ISSUE TITLE
Request for u360 analog firmware

### ISSUE THREAD

**Issue by Kinkeen22** [maziac/lagmeter#1]
I made an account just to try to contact you. I am trying to get a working copy of the firmware for output on analog outputs for my controllers. Can you help me if you are able?

**Comment by maziac** [comment]
I attached the firmware below.
For me it was working and I could also go back to flash another firmware.
But I don't know if there might be other Ultrastik HW versions that do not work with this firmware.
So, disclaimer, you do it at your own risk.

You could also try to contact Andy directly (you find the contact on the Ultimarc webpage).

[firmware removed]

(And, of course, unzip before flashing)

**Comment by Kinkeen22** [comment]
Thank you, but I also believe my hardware is too old of a version to flash this. The best I can do is 2.05. Talked to Andy and he stated as such. I'll probably just pick up a 2-axis hall effect sensor and wire it myself since I only want the analog outputs. Thank you again.
